#ifndef __KT_GLOBAL_DEF_H__
#define __KT_GLOBAL_DEF_H__

#include "cocos2d.h"

using namespace cocos2d;

enum eKTagType
{
	kTagDefault = 1000,

	kTagBtnSetup,
	kTagBtnScene,
	kTagBtnJinglingTuqian,
	kTagBtnJBHTuqian,
	kTagBtnBaoBao,  // 

	kTagBtnModeYd,
	kTagBtnModeMh,
	kTagBtnModeZy,

	kTagBtn123,
	// ------------------------------

	kTagBtnGuidHome,
	//kTagBtnGuidSave,
	kTagBtnGuidRestart,
    kTagBtnGuidSjjl,//随机精灵
	kTagBtnGuidPlayPre,
	kTagBtnGuidPlayNext,
    kTagElf,

	kTagPopGray,
	kTagEffSunLight,
	kTagEffBlueStar0,
	kTagEffBlueStar1,
	kTagEffBlueStar2,
	kTagElfHappy,
	kTagBlueStarBottom,
    
    //in elfDialog
    kTagBtnElf1,
    kTagBtnElf2,
    kTagBtnElf3,
    kTagBtnElf4,
    kTagBtnElf5,
    kTagBtnElf6,

    kTagBtnRedClose,//用于关闭精灵，场景，简笔画，画册等对话框
    //场景
    kTagBtnScene1,
    kTagBtnScene2,
    kTagBtnScene3,
    kTagBtnScene4,
    kTagBtnScene5,
    kTagBtnScene6,
    kTagBtnScene7,
    kTagBtnScene8,
    kTagBtnScene9,
    kTagBtnScene10,
    kTagBtnScene11,
    kTagBtnScene12,
    kTagBtnScene13,
    kTagBtnScene14,
    kTagBtnScene15,
    kTagBtnScene16,
    
    
    //简笔画
    kTagBtnFigure1,
    kTagBtnFigure2,
    kTagBtnFigure3,
    kTagBtnFigure4,
    kTagBtnFigure5,
    kTagBtnFigure6,
    kTagBtnFigure7,
    kTagBtnFigure8,
    kTagBtnFigure9,
    kTagBtnFigure10,
    kTagBtnFigure11,
    kTagBtnFigure12,
    kTagBtnFigure13,
    kTagBtnFigure14,
    kTagBtnFigure15,
    kTagBtnFigure16,
    kTagBtnFigure17,
    kTagBtnFigure18,
    kTagBtnFigure19,
    kTagBtnFigure20,
    kTagBtnFigure21,
    kTagBtnFigure22,
    kTagBtnFigure23,
    kTagBtnFigure24,
    kTagBtnFigure25,
    kTagBtnFigure26,
    kTagBtnFigure27,
    kTagBtnFigure28,
    kTagBtnFigure29,
    kTagBtnFigure30,
    kTagBtnFigure31,
    kTagBtnFigure32,
    kTagBtnFigure33,
    kTagBtnFigure34,
    kTagBtnFigure35,
    kTagBtnFigure36,
    kTagBtnFigure37,
    kTagBtnFigure38,
    kTagBtnFigure39,
    kTagBtnFigure40,
    kTagBtnFigure41,
    
    kTagBtnFigure1_below,
    kTagBtnFigure2_below,
    kTagBtnFigure3_below,
    
    //分享按钮
    kTagBtnQQZ,
    kTagBtnWX,
    kTagBtnXL,
    kTagBtnTXWB,
    
    //设置界面里的按钮
    kTagBtnHome,
    kTagBtnGSXinXi,
    kTagBtnJBSheZhi,
    kTagBtnShangDian,
    kTagBtnXuanChuan,
    
    //设置中的商店中的按钮
    kTagBtnLiBao,
    kTagBtnJianBiHua,
    kTagBtnJingling,
    kTagBtnFuWu,
    
    //商店里的按钮
    //简笔画
    kTagBtnJBHGoumai_1,
    kTagBtnJBHGoumai_2,
    kTagBtnJBHGoumai_3,
    kTagBtnJBHGoumai_4,
    kTagBtnJBHGoumai_5,
    kTagBtnJBHGoumai_6,
    kTagBtnJBHGoumai_7,
    kTagBtnJBHGoumai_8,
    
    kTagBtnJBHZongJia,
    
    //礼包
    kTagBtnLiBaoGoumai,
    //精灵
    kTagBtnJLGoumai_1,
    kTagBtnJLGoumai_2,
    kTagBtnJLGoumai_3,
    kTagBtnJLGoumai_4,
    kTagBtnJLGoumai_5,

    
    //基本设置下的按钮
    kTagBtnHuiFuGouMai,
    
    
    
    //增加了自由模式后新加的
    kTagBtnFreeHome,
    kTagBtnFreeSave,
    kTagBtnFreeRestart,
    kTagBtnFreeTX,
    kTagBtnFreeTD,
    kTagBtnFreePen,
    kTagBtnFreeRubber,
    kTagBtnFreeBg,
    kTagBtnFreeDj,
    
    //道具
    kTagBtnFreeDjbk1,
    kTagBtnFreeDjbk2,
    kTagBtnFreeDjbk3,
    kTagBtnFreeDjbk4,
    kTagBtnFreeDjbk5,
    kTagBtnFreeDjbk6,
    kTagBtnFreeDjbk7,
    kTagBtnFreeDjbk8,
    kTagBtnFreeDjbk9,
    kTagBtnFreeDjbk10,
    kTagBtnFreeDjbk11,
    kTagBtnFreeDjbk12,
    kTagBtnFreeDjbk13,
    kTagBtnFreeDjbk14,
    kTagBtnFreeDjbk15,
    kTagBtnFreeDjbk16,
    kTagBtnFreeDjbk17,
    kTagBtnFreeDjbk18,
    kTagBtnFreeDjbk19,
    kTagBtnFreeDjbk20,
    kTagBtnFreeDjbk21,
    kTagBtnFreeDjbk22,
    kTagBtnFreeDjbk23,
    kTagBtnFreeDjbk24,
    kTagBtnFreeDjbk25,
    kTagBtnFreeDjbk26,
    kTagBtnFreeDjbk27,
    kTagBtnFreeDjbk28,
    kTagBtnFreeDjbk29,
    kTagBtnFreeDjbk30,
    kTagBtnFreeDjbk31,
    kTagBtnFreeDjbk32,
    kTagBtnFreeDjbk33,
    kTagBtnFreeDjbk34,
    kTagBtnFreeDjbk35,
    kTagBtnFreeDjbk36,
    kTagBtnFreeDjbk37,
    kTagBtnFreeDjbk38,
    kTagBtnFreeDjbk39,
    kTagBtnFreeDjbk40,
    kTagBtnFreeDjbk41,
    kTagBtnFreeDjbk42,
    kTagBtnFreeDjbk43,
    kTagBtnFreeDjbk44,
    kTagBtnFreeDjbk45,
    kTagBtnFreeDjbk46,
    kTagBtnFreeDjbk47,
    kTagBtnFreeDjbk48,
    kTagBtnFreeDjbk49,
    kTagBtnFreeDjbk50,
    kTagBtnFreeDjbk51,
    kTagBtnFreeDjbk52,
    kTagBtnFreeDjbk53,
    kTagBtnFreeDjbk54,
    kTagBtnFreeDjbk55,
    kTagBtnFreeDjbk56,
    kTagBtnFreeDjbk57,
    kTagBtnFreeDjbk58,
    kTagBtnFreeDjbk59,
    kTagBtnFreeDjbk60,
    kTagBtnFreeDjbk61,
    kTagBtnFreeDjbk62,
    kTagBtnFreeDjbk63,
    kTagBtnFreeDjbk64,
    kTagBtnFreeDjbk65,
    kTagBtnFreeDjbk66,
    kTagBtnFreeDjbk67,
    kTagBtnFreeDjbk68,
    kTagBtnFreeDjbk69,
    kTagBtnFreeDjbk70,
    kTagBtnFreeDjbk71,
    kTagBtnFreeDjbk72,
    kTagBtnFreeDjbk73,
    kTagBtnFreeDjbk74,
    kTagBtnFreeDjbk75,
    kTagBtnFreeDjbk76,
    kTagBtnFreeDjbk77,
    kTagBtnFreeDjbk78,
    kTagBtnFreeDjbk79,
    kTagBtnFreeDjbk80,
    kTagBtnFreeDjbk81,
    kTagBtnFreeDjbk82,
    kTagBtnFreeDjbk83,
    kTagBtnFreeDjbk84,
    kTagBtnFreeDjbk85,
    kTagBtnFreeDjbk86,
    kTagBtnFreeDjbk87,
    kTagBtnFreeDjbk88,
    kTagBtnFreeDjbk89,
    kTagBtnFreeDjbk90,
    kTagBtnFreeDjbk91,
    kTagBtnFreeDjbk92,
    kTagBtnFreeDjbk93,
    kTagBtnFreeDjbk94,
    kTagBtnFreeDjbk95,
    kTagBtnFreeDjbk96,
    kTagBtnFreeDjbk97,
    kTagBtnFreeDjbk98,
    kTagBtnFreeDjbk99,
    kTagBtnFreeDjbk100,
    kTagBtnFreeDjbk101,
    kTagBtnFreeDjbk102,
    kTagBtnFreeDjbk103,
    kTagBtnFreeDjbk104,
    kTagBtnFreeDjbk105,
    kTagBtnFreeDjbk106,
    kTagBtnFreeDjbk107,
    kTagBtnFreeDjbk108,
    kTagBtnFreeDjbk109,
    kTagBtnFreeDjbk110,
    kTagBtnFreeDjbk111,
    kTagBtnFreeDjbk112,
    kTagBtnFreeDjbk113,
    kTagBtnFreeDjbk114,
    kTagBtnFreeDjbk115,
    kTagBtnFreeDjbk116,
    kTagBtnFreeDjbk117,
    kTagBtnFreeDjbk118,
    kTagBtnFreeDjbk119,
    kTagBtnFreeDjbk120,
    kTagBtnFreeDjbk121,
    kTagBtnFreeDjbk122,
    kTagBtnFreeDjbk123,
    kTagBtnFreeDjbk124,
    kTagBtnFreeDjbk125,
    kTagBtnFreeDjbk126,
    kTagBtnFreeDjbk127,
    kTagBtnFreeDjbk128,
    kTagBtnFreeDjbk129,
    kTagBtnFreeDjbk130,
    kTagBtnFreeDjbk131,
    kTagBtnFreeDjbk132,
    kTagBtnFreeDjbk133,
    kTagBtnFreeDjbk134,
    kTagBtnFreeDjbk135,
    kTagBtnFreeDjbk136,
    kTagBtnFreeDjbk137,
    kTagBtnFreeDjbk138,
    kTagBtnFreeDjbk139,
    kTagBtnFreeDjbk140,
    kTagBtnFreeDjbk141,
    kTagBtnFreeDjbk142,
    kTagBtnFreeDjbk143,
    kTagBtnFreeDjbk144,
    kTagBtnFreeDjbk145,
    kTagBtnFreeDjbk146,
    kTagBtnFreeDjbk147,
    kTagBtnFreeDjbk148,
    kTagBtnFreeDjbk149,
    kTagBtnFreeDjbk150,
    kTagBtnFreeDjbk151,
    kTagBtnFreeDjbk152,
    kTagBtnFreeDjbk153,
    kTagBtnFreeDjbk154,
    kTagBtnFreeDjbk155,
    kTagBtnFreeDjbk156,
    kTagBtnFreeDjbk157,
    kTagBtnFreeDjbk158,
    kTagBtnFreeDjbk159,
    kTagBtnFreeDjbk160,
    kTagBtnFreeDjbk161,
    kTagBtnFreeDjbk162,
    kTagBtnFreeDjbk163,
    kTagBtnFreeDjbk164,
    kTagBtnFreeDjbk165,
    kTagBtnFreeDjbk166,
    kTagBtnFreeDjbk167,
    kTagBtnFreeDjbk168,
    kTagBtnFreeDjbk169,
    kTagBtnFreeDjbk170,
    kTagBtnFreeDjbk171,
    kTagBtnFreeDjbk172,
    kTagBtnFreeDjbk173,
    kTagBtnFreeDjbk174,
    kTagBtnFreeDjbk175,
    kTagBtnFreeDjbk176,
    kTagBtnFreeDjbk177,
    kTagBtnFreeDjbk178,
    kTagBtnFreeDjbk179,
    kTagBtnFreeDjbk180,
    kTagBtnFreeDjbk181,
    kTagBtnFreeDjbk182,
    kTagBtnFreeDjbk183,
    kTagBtnFreeDjbk184,
    kTagBtnFreeDjbk185,
    kTagBtnFreeDjbk186,
    kTagBtnFreeDjbk187,
    kTagBtnFreeDjbk188,
    kTagBtnFreeDjbk189,
    kTagBtnFreeDjbk190,
    kTagBtnFreeDjbk191,
    kTagBtnFreeDjbk192,
    kTagBtnFreeDjbk193,
    kTagBtnFreeDjbk194,
    kTagBtnFreeDjbk195,
    kTagBtnFreeDjbk196,
    kTagBtnFreeDjbk197,
    kTagBtnFreeDjbk198,
    kTagBtnFreeDjbk199,
    kTagBtnFreeDjbk200,
    kTagBtnFreeDjbk201,
    kTagBtnFreeDjbk202,
    kTagBtnFreeDjbk203,
    kTagBtnFreeDjbk204,
    kTagBtnFreeDjbk205,
    kTagBtnFreeDjbk206,
    kTagBtnFreeDjbk207,
    kTagBtnFreeDjbk208,
    kTagBtnFreeDjbk209,
    kTagBtnFreeDjbk210,
    kTagBtnFreeDjbk211,
    kTagBtnFreeDjbk212,
    kTagBtnFreeDjbk213,
    kTagBtnFreeDjbk214,
    kTagBtnFreeDjbk215,
    kTagBtnFreeDjbk216,
    kTagBtnFreeDjbk217,
    kTagBtnFreeDjbk218,
    kTagBtnFreeDjbk219,
    kTagBtnFreeDjbk220,
    kTagBtnFreeDjbk221,
    kTagBtnFreeDjbk222,
    kTagBtnFreeDjbk223,
    kTagBtnFreeDjbk224,
    kTagBtnFreeDjbk225,
    kTagBtnFreeDjbk226,
    kTagBtnFreeDjbk227,
    kTagBtnFreeDjbk228,
    kTagBtnFreeDjbk229,
    kTagBtnFreeDjbk230,
    kTagBtnFreeDjbk231,
    kTagBtnFreeDjbk232,
    kTagBtnFreeDjbk233,
    kTagBtnFreeDjbk234,
    kTagBtnFreeDjbk235,
    kTagBtnFreeDjbk236,
    kTagBtnFreeDjbk237,
    kTagBtnFreeDjbk238,
    kTagBtnFreeDjbk239,
    kTagBtnFreeDjbk240,
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    kTagBtnFree001,
    kTagBtnFree002,
    kTagBtnFree003,
    kTagBtnFree004,
    kTagBtnFree005,
    kTagBtnFree006,
    kTagBtnFree007,
    kTagBtnFree008,
    kTagBtnFree009,
    kTagBtnFree010,
    kTagBtnFree011,
    kTagBtnFree012,
    kTagBtnFree013,
    kTagBtnFree014,
    kTagBtnFree015,
    kTagBtnFree016,
    kTagBtnFree017,
    kTagBtnFree018,
    kTagBtnFree019,
    kTagBtnFree020,
    kTagBtnFree021,
    kTagBtnFree022,
    kTagBtnFree023,
    kTagBtnFree024,
    kTagBtnFree025,
    kTagBtnFree026,
    kTagBtnFree027,
    kTagBtnFree028,
    kTagBtnFree029,
    kTagBtnFree030,
    kTagBtnFree031,
    kTagBtnFree032,
    kTagBtnFree033,
    kTagBtnFree034,
    kTagBtnFree035,
    kTagBtnFree036,
    kTagBtnFree037,
    kTagBtnFree038,
    kTagBtnFree039,
    kTagBtnFree040,
    kTagBtnFree041,
    kTagBtnFree042,
    kTagBtnFree043,
    kTagBtnFree044,
    
    //图册下的删除和取消按钮
    kTagBtnDelete,
    kTagBtnCancel,
    
    //描红模式下增加的按钮
    kTagBtnStrokeHome,
    kTagBtnStrokeRestart,
    kTagBtnStrokeStep,
    kTagBtnStrokeSelect,
    kTagBtnStrokeScore,
    kTagBtnStrokePen,
    kTagBtnStrokeEraser,
    kTagBtnStrokeRadiusMinus,
    kTagBtnStrokeRadiusPlus,
    kTagBtnStrokePicItem0,
    kTagBtnStrokePicItem1,
    kTagBtnStrokePicItem2,
    kTagBtnStrokePicItem3,
    kTagBtnStrokePicItem4,
    kTagBtnStrokePicItem5,
    kTagBtnStrokePicItem6,
    kTagBtnStrokePicItem7,
    kTagBtnStrokePicItem8,
    kTagBtnStrokePicItem9,
    kTagBtnStrokePicItem10,
    kTagBtnStrokePicItem11,
    kTagBtnStrokePicItem12,
    kTagBtnStrokePicItem13,
    kTagBtnStrokePicItem14,
    kTagBtnStrokePicItem15,
    kTagBtnStrokePicItem16,
    kTagBtnStrokePicItem17,
    kTagBtnStrokePicItem18,
    kTagBtnStrokePicItem19,
    kTagBtnStrokePicItem20,
    kTagBtnStrokePicItem21,
    kTagBtnStrokePicItem22,
    kTagBtnStrokePicItem23,
    kTagBtnStrokePicItem24,
    kTagBtnStrokePicItem25,
    kTagBtnStrokePicItem26,
    kTagBtnStrokePicItem27,
    kTagBtnStrokePicItem28,
    kTagBtnStrokePicItem29,
    kTagBtnStrokePicItem30,
    kTagBtnStrokePicItem31,
    kTagBtnStrokePicItem32,
    kTagBtnStrokePicItem33,
    kTagBtnStrokePicItem34,
    kTagBtnStrokePicItem35,
    kTagBtnStrokePicItem36,
    kTagBtnStrokePicItem37,
    kTagBtnStrokePicItem38,
    kTagBtnStrokePicItem39,
    kTagBtnStrokePicItem40,
    kTagBtnStrokePicItem41,
    kTagBtnStrokePicItem42,
    kTagBtnStrokePicItem43,
    kTagBtnStrokePicItem44,
    kTagBtnStrokePicItem45,
    kTagBtnStrokePicItem46,
    kTagBtnStrokePicItem47,
    kTagBtnStrokePicItem48,
    kTagBtnStrokePicItem49,
    kTagBtnStrokePicItem50,
    kTagBtnStrokePicItem51,
    kTagBtnStrokePicItem52,
    kTagBtnStrokePicItem53,
    kTagBtnStrokePicItem54,
    kTagBtnStrokePicItem55,
    kTagBtnStrokePicItem56,
    kTagBtnStrokePicItem57,
    kTagBtnStrokePicItem58,
    kTagBtnStrokePicItem59,
    kTagBtnStrokePicItem60,
    kTagBtnStrokePicItem61,
    kTagBtnStrokePicItem62,
    kTagBtnStrokePicItem63,
    kTagBtnStrokePicItem64,
    kTagBtnStrokePicItem65,
    kTagBtnStrokePicItem66,
    kTagBtnStrokePicItem67,
    kTagBtnStrokePicItem68,
    kTagBtnStrokePicItem69,
    kTagBtnStrokePicItem70,
    kTagBtnStrokePicItem71,
    kTagBtnStrokePicItem72,
    kTagBtnStrokePicItem73,
    kTagBtnStrokePicItem74,
    kTagBtnStrokePicItem75,
    kTagBtnStrokePicItem76,
    kTagBtnStrokePicItem77,
    kTagBtnStrokePicItem78,
    kTagBtnStrokePicItem79,
    kTagBtnStrokePicItem80,
    kTagBtnStrokePicItem81,
    kTagBtnStrokePicItem82,
    kTagBtnStrokePicItem83,
    kTagBtnStrokePicItem84,
    kTagBtnStrokePicItem85,
    kTagBtnStrokePicItem86,
    kTagBtnStrokePicItem87,
    kTagBtnStrokePicItem88,
    kTagBtnStrokePicItem89,
    kTagBtnStrokePicItem90,
    kTagBtnStrokePicItem91,
    kTagBtnStrokePicItem92,
    kTagBtnStrokePicItem93,
    kTagBtnStrokePicItem94,
    kTagBtnStrokePicItem95,
    kTagBtnStrokePicItem96,
    kTagBtnStrokePicItem97,
    kTagBtnStrokePicItem98,
    kTagBtnStrokePicItem99,
    kTagBtnStrokePicItem100,
    kTagBtnStrokePicItem101,
    kTagBtnStrokePicItem102,
    kTagBtnStrokePicItem103,
    kTagBtnStrokePicItem104,
    kTagBtnStrokePicItem105,
    kTagBtnStrokePicItem106,
    kTagBtnStrokePicItem107,
    kTagBtnStrokePicItem108,
    kTagBtnStrokePicItem109,
    kTagBtnStrokePicItem110,
    kTagBtnStrokePicItem111,
    kTagBtnStrokePicItem112,
    kTagBtnStrokePicItem113,
    kTagBtnStrokePicItem114,
    kTagBtnStrokePicItem115,
    kTagBtnStrokePicItem116,
    kTagBtnStrokePicItem117,
    kTagBtnStrokePicItem118,
    kTagBtnStrokePicItem119,
    kTagBtnStrokePicItem120,
    kTagBtnStrokePicItem121,
    kTagBtnStrokePicItem122,
    
    
    //next&previous& start
//    新增的上一步和下一步按钮
    kTagBtnNext_elf,
    kTagBtnBack_jbh,
    kTagBtnNext_jbh,
    kTagBtnBack_scene,
    kTagBtnStart_scene,
    
    //小蓝方框
    kTagBtnSquareBlueRing,
    
    
    
};

enum eZOrder
{
	zTagDefault = 0,

	zTagBtnRefresh,
    
    zUiRoot = 1000,
    
    
};

#define MSG_EVENT_GAME_FINISH "game_finish" // 


#endif // __KT_GLOBAL_DEF_H__